### ISSUE TITLE
Crash when enumerating Peer DB

### ISSUE THREAD

**Issue by hank** [Litecoin-Java/bitcoin-wallet#45]
```
java.util.NoSuchElementException
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:576)
at com.google.bitcoin.net.discovery.PeerDBDiscovery.getPeers(PeerDBDiscovery.java:289)
at de.schildbach.wallet.service.BlockchainServiceImpl$3$1.getPeers(BlockchainServiceImpl.java:439)
at com.google.bitcoin.core.PeerGroup.discoverPeers(PeerGroup.java:502)
at com.google.bitcoin.core.PeerGroup.connectToAnyPeer(PeerGroup.java:553)
at com.google.bitcoin.core.PeerGroup.run(PeerGroup.java:531)
at com.google.common.util.concurrent.AbstractExecutionThreadService$1$1.run(AbstractExecutionThreadService.java:52)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by TheBlueMatt** [comment]
Are you running the latest version in https://github.com/bitcoinj/bitcoinj/pull/2/files ? I dont see a way this could happen? Any further debugging you could provide.

**Comment by hank** [comment]
I'll make sure I merge that if I haven't already - thanks!  I pulled this from Google's crash reporter.

**Comment by hank** [comment]
I believe this is fixed in this commit:
https://github.com/Litecoin-Java/bitcoinj/commit/90dd6e1747062361ca4e53aa1c634d6991f15890

**Comment by hank** [comment]
From your pull request:

``` java
Iterator<PeerData> iterator = peerList.iterator();
for (int i = 0; i < addressesToReturn; i++) {
  PeerData peer = iterator.next();
```

You're calling .next() without checking hasNext(), which causes the exception seen above on an empty list.

**Comment by TheBlueMatt** [comment]
That shouldn't be necessary, it's all in a synchronized method and the number of times next is called is less than size()
