### ISSUE TITLE
Negative outputs crash the app

### ISSUE THREAD

**Issue by hank** [Litecoin-Java/bitcoin-wallet#50]
Looks like someone tried to put in a negative number perhaps?  WTF happened here?  From Developer Console crash reports.

```
java.lang.IllegalArgumentException: Negative values not allowed
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
at com.google.bitcoin.core.TransactionOutput.<init>(TransactionOutput.java:111)
at com.google.bitcoin.core.TransactionOutput.<init>(TransactionOutput.java:95)
at com.google.bitcoin.core.Transaction.addOutput(Transaction.java:732)
at com.google.bitcoin.core.Wallet$SendRequest.to(Wallet.java:1599)
at de.schildbach.wallet.ui.SendCoinsFragment.handleGo(SendCoinsFragment.java:897)
at de.schildbach.wallet.ui.SendCoinsFragment.access$1800(SendCoinsFragment.java:107)
at de.schildbach.wallet.ui.SendCoinsFragment$7.onClick(SendCoinsFragment.java:466)
at android.view.View.performClick(View.java:4475)
at android.view.View$PerformClick.run(View.java:18786)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5419)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
at dalvik.system.NativeStart.main(Native Method)
```

Perhaps we should make sure one can't enter negative amounts, but I thought that was the case already.

**Comment by hank** [comment]
Just tried and my phone won't let me enter a negative amount..  Going with wontfix.
